name: CD

on:
  # Triggers the workflow when new releases are created
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: Setup
        run: yarn install
      - name: Format
        run: npm run format
      - name: Fix
        run: npm run lint-fix

      - name: Auto committing styled files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: 'src/'
          commit_message: "Github Action: Auto styled JS files"
          branch: ${{ github.ref }}
          add_options: '-f'

      - name: Auto Minify
        uses: nizarmah/auto-minify@v2.0
        with:
          directory: 'src'
          output: 'dist'
          js_engine: uglify-js
      
      - name: Publish
        run: npm publish --access public
        env:
            NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
            
